### PR TITLE
fix(error-case ): fix deserialization exception in error template message

### LINKED ISSUE #27: Error message template incase of nill response  raw body while mapping response.body placeholder results into deserialization error
**Describe the bug**
Error message template incase of nil response  raw body while mapping response.body placeholder results into deserialization error

**Expected behavior**
We should not deserialize incase of nil and empty response when mapping the body_placeholder

**Screenshots**
If applicable, add screenshots to help explain the bug.
image

**Library version number**
For example:  0.3.0

### PR DESCRIPTION
**Pull request by MaryamAdnan3**
fix(error-case ): fix deserialization exception in **_get_resolved_error_message_template**
closes #27

## What
Handle deserialization exception in error template message

## Why
response_body placeholder should be replaced with a empty value incase of any unsuccessful deserialized response
## Type of change
Select multiple if applicable.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [ ] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
If a new dependency is being added, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Policy-of-adding-new-dependencies-in-the-core-libraries

## Breaking change
If the PR is introducing a breaking change, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Guidelines-for-maintaining-core-libraries

## Testing
List the steps that were taken to test the changes

## Checklist
- [ ] My code follows the coding conventions
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added new unit tests

### CODE REVIEW

File: lib/apimatic-core/types/error_case.rb [hunk 1]
```diff
@@ -68,7 +68,12 @@ def _get_resolved_error_message_template(response)
                                                                        error_message_template)
 
       # Handling response body placeholder
-      response_payload = ApiHelper.json_deserialize(response.raw_body, true)
+      begin
+        response_payload = ApiHelper.json_deserialize(response.raw_body, true) unless response.raw_body.nil?
+      rescue TypeError
+        response_payload = nil
```
Comment (sufyankhanrao) [inline lib/apimatic-core/types/error_case.rb:74]: Question: Is this unit tested? If not, kindly add a unit test against this case.

**Review by sufyankhanrao — CHANGES_REQUESTED** [review]

File: lib/apimatic-core/types/error_case.rb (hunk 1 above)
Comment (sufyankhanrao) [reply lib/apimatic-core/types/error_case.rb:74]: Test case added.
