### PR TITLE
fix(file-handling): file not being closed after opening and caching

### LINKED ISSUE #60: [Bug] Opened file is not being closed in filehelper class
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The file is opened but not being closed after updating the cache.

### Expected Behavior

The file should be properly closed before caching in the application memory.

### Steps To Reproduce

1. Use core library with the SDK where files are being sent in the request

### Environment

```markdown
- **OS**: Win
- **Language version**: 3.1
- **SDK Name**:
```

### Relevant log output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sufyankhanrao**
## What
This PR fixes the file writing to the temp directory which is then cached. The file is created but is not being closed in the flow while getting the file in file helper class.

## Why
This issue causes exception when sending the file in request parameters in the SDK.

Closes #60 

## Type of change
Select multiple if applicable.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause a breaking change)
- [ ] Tests (adds or updates tests)
- [ ] Documentation (adds or updates documentation)
- [ ] Refactor (style improvements, performance improvements, code refactoring)
- [ ] Revert (reverts a commit)
- [ ] CI/Build (adds or updates a script, change in external dependencies)

## Dependency Change
If a new dependency is being added, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Policy-of-adding-new-dependencies-in-the-core-libraries

## Breaking change
If the PR is introducing a breaking change, please ensure that it adheres to the following guideline https://github.com/apimatic/apimatic-codegen/wiki/Guidelines-for-maintaining-core-libraries

## Testing
List the steps that were taken to test the changes

## Checklist
- [x] My code follows the coding conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added new unit tests

### CODE REVIEW

File: lib/apimatic-core/utilities/file_helper.rb [hunk 1]
```diff
@@ -1,21 +1,27 @@
...
   class FileHelper
     @cache = {}
 
-    # Class method which takes a URL, downloads the file (if not already downloaded.
-    # for this test session) and returns the path of the file.
+    # Class method which takes a URL, downloads the file (if not already downloaded
+    # for this test session), and returns the file path.
     # @param [String] url The URL of the required file.
+    # @return [String] The path of the downloaded file.
     def self.get_file(url)
```
Comment (MaryamAdnan3) [inline lib/apimatic-core/utilities/file_helper.rb:13]: Do we have an existing test that verifies this functionality

Comment (sufyankhanrao) [reply lib/apimatic-core/utilities/file_helper.rb:13]: Are you talking about the exception case?

Comment (MaryamAdnan3) [reply lib/apimatic-core/utilities/file_helper.rb:13]: yes

Comment (sufyankhanrao) [reply lib/apimatic-core/utilities/file_helper.rb:13]: No, we don't have such tests.

Comment (sufyankhanrao) [reply lib/apimatic-core/utilities/file_helper.rb:13]: This is a case of race condition that we were previously facing through the SDKs which occurs randomly. So if the behavior is random then adding tests won't be a good here.

Comment (MaryamAdnan3) [reply lib/apimatic-core/utilities/file_helper.rb:13]: yes that makes sense as it's flaky behavior.
